"""Add SentEmail tracking model

Revision ID: 5ed4e2b9648a
Revises: 20260516_0003
Create Date: 2026-07-12 10:30:09.304993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5ed4e2b9648a'
down_revision: Union[str, None] = '20260516_0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
